version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: promanage_db
    environment:
      POSTGRES_DB: promanage_db
      POSTGRES_USER: promanage_user
      POSTGRES_PASSWORD: promanage_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U promanage_user -d promanage_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - promanage_network

volumes:
  postgres_data:
    name: promanage_postgres_data

networks:
  promanage_network:
    name: promanage_network
