name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'back-end/**'
      - '.github/workflows/backend-ci-cd.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'back-end/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          cd back-end
          npm ci
      
      # Les tests ne sont pas encore implémentés, on les ignore pour l'instant
      - name: Skip tests
        run: |
          cd back-end
          echo "Skipping tests for now"
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./back-end
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/promanage-backend:latest, ${{ secrets.DOCKERHUB_USERNAME }}/promanage-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
